export interface Company {
    id?: number,
    cnpj: string,
    name: string,
    email: string,
    phone_number: string,
    number: string,
    cep: string,
    uf: string,
    password: string,
    password_confirmation: string,
    complement: string,
    address: string,
    district: string,
    city: string,
}